<?php

$navigation = new Micro\Navigation\Navigation([
    ['label' => 'Начало', 'route' => 'home'],
    ['label' => 'Вход', 'route' => 'login'],
    ['label' => 'Регистрация', 'route' => 'register'],
    ['label' => 'Профил', 'route' => 'profile'],
    ['label' => 'Права', 'route' => 'rights'],
    ['label' => 'Градове', 'route' => 'default', 'routeParams' => ['package' => 'nomenclatures', 'controller' => 'cities']],
    ['label' => 'Държави', 'route' => 'default', 'routeParams' => ['package' => 'nomenclatures', 'controller' => 'countries']],
    ['label' => 'Изход', 'route' => 'logout'],
]);

$tmp = '<ul class="nav">' . PHP_EOL;

foreach ((new \RecursiveIteratorIterator($navigation, \RecursiveIteratorIterator::SELF_FIRST)) as $page) {
    if (!$page->hasAccess()) {
        continue;
    }
    if ($page->isActive(\true)) {
        $tmp .= '<li><span>' . $page->getLabel() . '</span></li>' . PHP_EOL;
    } else {
        $tmp .= '<li><a href="' . $page->getHref() . '">' . $page->getLabel() . '</a></li>' . PHP_EOL;
    }
}

$tmp .= '</ul>' . PHP_EOL;

echo $tmp;