<ul class="nav">
    <li><a href="<?php echo route('home'); ?>">home</a></li>
<?php if (identity()) : ?>
    <li><a href="<?php echo route('default', ['package' => 'nomenclatures', 'controller' => 'countries'], \true); ?>">countries</a></li>
    <li><a href="<?php echo route('profile'); ?>">profile</a></li>
    <li><a href="<?php echo route('logout'); ?>">logout</a></li>
<?php else : ?>
    <li><a href="<?php echo route('login'); ?>">login</a></li>
    <li><a href="<?php echo route('register'); ?>">register</a></li>
<?php endif;  ?>
</ul>