<ul class="nav">
    <li><a href="<?php echo route('home'); ?>">Начало</a></li>
<?php if (identity()) : ?>
    <li><a href="<?php echo route('rights'); ?>">Права</a></li>
    <li><a href="<?php echo route('default', ['package' => 'nomenclatures', 'controller' => 'cities'], \true); ?>">Градове</a></li>
    <li><a href="<?php echo route('default', ['package' => 'nomenclatures', 'controller' => 'countries'], \true); ?>">Държави</a></li>
    <li><a href="<?php echo route('profile'); ?>">Профил</a></li>
    <li><a href="<?php echo route('logout'); ?>">Изход</a></li>
<?php else : ?>
    <li><a href="<?php echo route('login'); ?>">Вход</a></li>
    <li><a href="<?php echo route('register'); ?>">Регистрация</a></li>
<?php endif;  ?>
</ul>