<!DOCTYPE html>
<html lang="en">
<head>
    <base href="<?php echo server_url(base_url()) . '/'; ?>" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><?php echo $this->renderSection('title', 'Home'); ?></title>
    <link rel="stylesheet" href="assets/templates/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/templates/bootstrap/extends/datepicker/css/bootstrap-datepicker3.standalone.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/templates/bootstrap/extends/font-awesome-4.4.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="assets/templates/bootstrap/extends/summernote/summernote.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/templates/bootstrap/extends/select/css/bootstrap-select.min.css" rel="stylesheet">
    <link rel="stylesheet" href="assets/templates/bootstrap/css/custom.css" rel="stylesheet">
    <?php echo $this->renderSection('styles'); ?>
</head>
<body role="document">
    <?php echo $this->partial('layouts/includes/_menu'); ?>
    <div class="container-fluid">
        <?php echo $this->partial('layouts/includes/_flash'); ?>
        <?php echo $this->renderSection('content'); ?>
    </div>
    <footer class="footer">
        <div class="container">
            <p class="text-muted">Copyright © <?php echo date('Y'); ?></p>
        </div>
    </footer>
    <?php echo $this->renderSection('scripts'); ?>
</body>
</html>